AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Spring Boot Lambda API

Resources:
  SpringBootLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.example.lambda.handler.LambdaHandler
      Runtime: java17
      CodeUri: .
      MemorySize: 1024
      Timeout: 30
      Policies: AWSLambdaBasicExecutionRole
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
